@startuml
left to right direction
() USERAPP
() DRIVERAPP

package "geoservices" {
  [GEOFENCING]
  [VICINITY]
  [ROUTING]
  [TIMING]
}

package "ridemanagementservices" {
    [CABSTATEMACHINESERVICE]
    [CABSTATEMANAGEMENT]
    [TRIPMANAGEMENT]
    [DISPUTESERVICE]
}

package "geoserver" {
    [TILE38]
}

VICINITY <-> TILE38
ROUTING <-> TILE38

CABSTATEMACHINESERVICE <-> CABSTATEMANAGEMENT
CABSTATEMACHINESERVICE <-> TRIPMANAGEMENT
CABSTATEMACHINESERVICE <- VICINITY
CABSTATEMACHINESERVICE <- ROUTING
CABSTATEMACHINESERVICE <- TIMING

USERAPP -> GEOFENCING
DRIVERAPP -> GEOFENCING
DRIVERAPP -> CABSTATEMACHINESERVICE
USERAPP -> CABSTATEMACHINESERVICE
USERAPP -> TRIPMANAGEMENT
DRIVERAPP -> TRIPMANAGEMENT
USERAPP -> DISPUTESERVICE
DRIVERAPP -> DISPUTESERVICE
center footer Generated for demonstration
@enduml