package com.demo.booking.cabbooking.statemachine;

public enum CabStates {
    OFFLINE,
    READYTORIDE,
    READYTORIDEWITHDELAY,
    WAITINGFORDRIVERCONFIRMATION,
    WAITINGFORUSERCONFIRMATION,
    RIDECONFIRMED,
    REACHINGPICKUPLOCATION,
    WAITINGFORPASSENGER,
    RIDEINPROGRESS
}
