package com.demo.booking.cabbooking.statemachine;

public enum RideEvents {
    OFFLINEREQUESTED,
    ONLINEREQUESTED,
    DRIVERCONFIRMED,
    USERCONFIRMED,
    RIDEREQUESTED,
    RIDEBOOKED,
    ARRIVEDATPICKUPLOCATION,
    PASSENGERNOSHOW,
    PASSENGERARRIVED,
    RIDECANCELED,
    RIDECOMPLETED,
}
